### PR TITLE
CVR-784  Move build warnings to a list

### PR DESCRIPTION
**Pull request by hobbitronics**
[CVR-784](https://itse.youtrack.cloud/issue/CVR-784/clean-up-build-warnings)

## Change
- move remaining warnings to a filter list with a Todo
- update svelte-preprocess to remove a warning

see https://github.com/rollup/rollup/issues/408 for more info on filtering warnings

### CODE REVIEW

**Review by mtompset — APPROVED** [review]
My review doesn't count for much given a lack of familiarity with the code, but I think it is okay.

**Comment by briskt** [comment]
> My inclination is to avoid filtering out the warnings, letting them keep showing until we fix them, but that's just a hunch/preference.

If I was pressed, I'd say the same. But not knowing the implications of these warnings, I can't really say how important it is to address them.

**Review by forevermatt — APPROVED** [review]
@hobbitronics As long as we will still have a YouTrack issue open about coming back and fixing these warnings that will now be hidden, I'm fine if you proceed with merging this.

**Comment by hobbitronics** [comment]
Down to one [CVR-788](https://itse.youtrack.cloud/issue/CVR-788/fix-A11y-noninteractive-element-cannot-have-nonnegative-tabIndex-value)

**Pull request merged**
