### PR TITLE
update ui-components and run npm update

### PR DESCRIPTION
**Pull request by hobbitronics**
- ui-components updated to 3.9.0
- ran `npm update`
(I only tested the build without an api and will be on the road for a few hours so someone could test the app a little locally or we could just test on staging)

### CODE REVIEW

**Comment by forevermatt** [comment]
@hobbitronics - Did you close this PR (without merging it) on purpose? Just wanted to confirm, since it looks like that feature branch hasn't been merged or deleted.

**Comment by hobbitronics** [comment]
@forevermatt yes. Somehow the build failed and I just decided to update ui-components.

**Comment by forevermatt** [comment]
> @forevermatt yes. Somehow the build failed and I just decided to update ui-components.

Okay, thanks. Is it okay if I delete the unmerged feature branch, then?

**Comment by hobbitronics** [comment]
yeah. Go ahead. Thanks.

**Comment by hobbitronics** [comment]
Actually I just did.

**Pull request closed without merging**
