### PR TITLE
Release - add Sentry

### PR DESCRIPTION
**Pull request by hobbitronics**
### Added

- Added Sentry

### Changed

- update deps

### Feature branch checklist

- [ ] Documentation (README, etc.)
- [ ] Run `make format`, `make lint` and `make check`

### CODE REVIEW

**Review by briskt — APPROVED** [review]

**Comment by briskt** [comment]
Something seems to be broken on staging

**Comment by hobbitronics** [comment]
> Something seems to be broken on staging

Thanks, pushed a fix for that.

**Comment by hobbitronics** [comment]
> > Something seems to be broken on staging
> 
> Thanks, pushed a fix for that.

Still isn't working properly. The ui partially shows up, but not making a users/me call

**Comment by hobbitronics** [comment]
> > > Something seems to be broken on staging
> > 
> > 
> > Thanks, pushed a fix for that.
> 
> Still isn't working properly. The ui partially shows up, but not making a users/me call

Should be working now.

**Comment by briskt** [comment]
Does `tracePropagationTargets` still need to be commented?

**Review by briskt — APPROVED** [review]
Would be nice if there was a better way to inject the environment variables for the prebuild:prod script.

**Comment by hobbitronics** [comment]
> Would be nice if there was a better way to inject the environment variables for the prebuild:prod script.

Not aware of any other way still, but yeah.

**Comment by hobbitronics** [comment]
> Does `tracePropagationTargets` still need to be commented?

I don't know what this does yet, but the example code they give probably should be commented out until I have something better or decide it's not needed. I all a YT issue.

**Pull request merged**
