### PR TITLE
change claimStates.Revew3.title

### PR DESCRIPTION
**Pull request by hobbitronics**
- update title to "Awaiting review 3/3" https://trello.com/c/fCN5ZgVv/333-clarify-review-process

### CODE REVIEW

**Review by RussellChamp — APPROVED** [review]
nice. why did i think we were using messages returned by the BE?

**Comment by hobbitronics** [comment]
> nice. why did i think we were using messages returned by the BE?

You were probably thinking of claim.status_reason.

**Comment by merchako** [comment]
Do we have different state callout text coded for customers vs stewards, or are they both the same?

**Comment by hobbitronics** [comment]
> Do we have different state callout text coded for customers vs stewards, or are they both the same?

yes they are different. There is a state getter function that is supposed to retrieve claim states for admins vs customers.

**Pull request merged**
