### PR TITLE
use cookies instead of session storage CVR-610

### PR DESCRIPTION
**Pull request by hobbitronics**
[CVR-610](https://itse.youtrack.cloud/issue/CVR-610)

### Added

- Cookies library 🍪

### Changed

- token is now stored in a cookie 🍪

### Feature branch checklist

- [ ] Documentation (README, etc.)
- [x] Run `make format`, `make lint` and `make check`

### CODE REVIEW

**Review by briskt — APPROVED** [review]

**Review by forevermatt — COMMENTED** [review]
Moving this over from sessionStorage to a cookie means it will automatically be included in all web requests to the host. Is that desired? Are we then including it twice?

Just a couple of questions to sort through before proceeding all the way to production with this.

**Comment by hobbitronics** [comment]
> Moving this over from sessionStorage to a cookie means it will automatically be included in all web requests to the host. Is that desired? Are we then including it twice?
> 
> Just a couple of questions to sort through before proceeding all the way to production with this.

Good call @forevermatt. I See where we can make those changes on the UI, but I think this will have to happen with some changes to the api, to be able to use the cookie in the request headers.

**Review by briskt — CHANGES_REQUESTED** [review]
After further thought, I'd like to know if this can be done with most of the work happening on the backend.

**Comment by hobbitronics** [comment]
I agree with @briskt on this being done on the backend as httpOnly cookies won't be accessible via Javascript.

**Pull request closed without merging**
