### PR TITLE
add hsts header

### PR DESCRIPTION
**Pull request by hobbitronics**
image

### CODE REVIEW

**Review by forevermatt — APPROVED** [review]

**Review by forevermatt — CHANGES_REQUESTED** [review]
I think this actually has to come from the server... sending it as part of the request headers is, I think, ineffective.

**Comment by Baggerone** [comment]
> I think this actually has to come from the server... sending it as part of the request headers is, I think, ineffective.

@forevermatt What do you mean by `the server`, the `cover-api`?

**Comment by forevermatt** [comment]
> > I think this actually has to come from the server... sending it as part of the request headers is, I think, ineffective.
> 
> @forevermatt What do you mean by `the server`, the `cover-api`?

Whichever server is responding to the HTTP / HTTPS requests that we are trying to ensure are requested using HTTPS. In this case, I think the goal is to use this HSTS header to get the UI to be served more reliably over HTTPS, but the header was added in JavaScript calls from the UI to the API. It needs to be added to the webserver response that is serving up the UI files (which might be Cloudflare pages, in this case).

**Comment by hobbitronics** [comment]
> > > I think this actually has to come from the server... sending it as part of the request headers is, I think, ineffective.
> > 
> > 
> > @forevermatt What do you mean by `the server`, the `cover-api`?
> 
> Whichever server is responding to the HTTP / HTTPS requests that we are trying to ensure are requested using HTTPS. In this case, I think the goal is to use this HSTS header to get the UI to be served more reliably over HTTPS, but the header was added in JavaScript calls from the UI to the API. It needs to be added to the webserver response that is serving up the UI files (which might be Cloudflare pages, in this case).

I think you are correct about it being Cloudflare. There were instructions on how to do this in [HSTS for Cover](https://itse.youtrack.cloud/issues?q=project%3A%20%7BETH%7D&preview=CVR-9)

**Pull request closed without merging**
