### PR TITLE
Stop using Google Places API

### PR DESCRIPTION
**Pull request by forevermatt**
### Changed
- Stop using the Google Places Autocomplete API, to prepare for simpler country-select design

---

When all we're really interested in is the country, using a list of countries from the database works better:

- It avoids needing to adding the Google Maps/Places API to our privacy policy.
- It paves the way for future expectations of limiting certain coverage based on country.
- It avoids the problem of that Google API not allowing us to filter to just countries anyway.

### CODE REVIEW

**Review by hobbitronics — APPROVED** [review]
I unnaprove this... er approve this pull regress.

**Review by hobbitronics — COMMENTED** [review]
Just wondering if you are leaving the env in there intentionally.

**Comment by forevermatt** [comment]
> Just wondering if you are leaving the env in there intentionally.

Nope 🤦

**Review by hobbitronics — APPROVED** [review]
re-approved

**Pull request merged**
